sudo: required
dist: trusty

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get -qq update
  - sudo apt-get install libsdl2-dev
