[package]
name = "rgb"
version = "0.1.0"
authors = ["NivenT <nachenjang@gmail.com>"]

[dependencies]
glium_sdl2 = "0.13.0"
glium_text = "0.10.0"
sdl2 = "0.27.0"
glium = "0.15.0"
tini = "0.1.1"
time = "0.1.35"
fps_clock = "2.0"
rodio = "0.14.0"
