use emulator::registers::Registers;

macro_rules! new_cb_instruction {
    ($name:expr, $func:expr) => {
    	CBInstruction{name: $name, func: $func}
    }
}

pub type CBInstructionFunc = Option<&'static Fn(&mut Registers) -> ()>;

#[derive(Copy, Clone)]
pub struct CBInstruction {
	pub name:			&'static str,
	pub func:			CBInstructionFunc
}

pub const CB_INSTRUCTIONS: [CBInstruction; 256] = [
	//0x00
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x08
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x10
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x18
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x20
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x28
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x30
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x38
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x40
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x48
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x50
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x58
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x60
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x68
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x70
	new_cb_instruction!("BIT 6,B", None),
	new_cb_instruction!("BIT 6,C", None),
	new_cb_instruction!("BIT 6,D", None),
	new_cb_instruction!("BIT 6,E", None),
	new_cb_instruction!("BIT 6,H", None),
	new_cb_instruction!("BIT 6,L", None),
	new_cb_instruction!("BIT 6,(HL)", None),
	new_cb_instruction!("BIT 6,A", None),
	//0x78
	new_cb_instruction!("BIT 7,B", None),
	new_cb_instruction!("BIT 7,C", None),
	new_cb_instruction!("BIT 7,D", None),
	new_cb_instruction!("BIT 7,E", None),
	new_cb_instruction!("BIT 7,H", None),
	new_cb_instruction!("BIT 7,L", None),
	new_cb_instruction!("BIT 7,(HL)", None),
	new_cb_instruction!("BIT 7,A", None),
	//0x80
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x88
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x90
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0x98
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xA0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xA8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xB0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xB8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xC0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xC8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xD0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xD8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xE0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xE8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xF0
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	//0xF8
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None),
	new_cb_instruction!("", None)
];